### ISSUE TITLE
Error: spawn EMFILE

### ISSUE THREAD

**Issue by tiagoporto** [sindresorhus/gulp-imagemin#10]
What is this error?

```
child_process.js:935
    throw errnoException(process._errno, 'spawn');
          ^
Error: spawn EMFILE
    at errnoException (child_process.js:988:11)
    at ChildProcess.spawn (child_process.js:935:11)
    at exports.spawn (child_process.js:723:9)
    at Imagemin._optimizePng (/Volumes/DEVEAD/WAMP/www/moodle/theme/numeramento/node_modules/gulp-imagemin/node_modules/image-min/imagemin.js:151:12)
    at Imagemin.optimize (/Volumes/DEVEAD/WAMP/www/moodle/theme/numeramento/node_modules/gulp-imagemin/node_modules/image-min/imagemin.js:63:26)
    at module.exports (/Volumes/DEVEAD/WAMP/www/moodle/theme/numeramento/node_modules/gulp-imagemin/node_modules/image-min/imagemin.js:189:21)
    at /Volumes/DEVEAD/WAMP/www/moodle/theme/numeramento/node_modules/gulp-imagemin/index.js:38:5
    at Object.oncomplete (fs.js:107:15)
```

**Comment by oluul** [comment]
ulimit -S -n 8196 # worked!

**Comment by marek1** [comment]
ulimit -S -n 2048 worked . thanks.
