### ISSUE TITLE
Error: write EPIPE on imagemin-gifsicle

### ISSUE THREAD

**Issue by kud** [sindresorhus/gulp-imagemin#106]
Windows 7 with node v0.12.2

```javascript
var gulp     = require('gulp')
var imagemin = require('gulp-imagemin')

module.exports = function() {

  return gulp.src('src/images/**/*')
    .pipe( imagemin() )
    .pipe( gulp.dest('dist/images') )

}
```

```console
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at Socket._writeGeneric (net.js:690:26)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at Socket.Writable.end (_stream_writable.js:449:10)
    at Socket.end (net.js:415:31)
    at Through2._transform (D:\Projects\_kud\diary\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\index.js:68:12)
jake aborted.
Error: Process exited with error.
    at api.fail (C:\Users\Kud\AppData\Roaming\npm\node_modules\jake\lib\api.js:336:18)
    at null.<anonymous> (C:\Users\Kud\AppData\Roaming\npm\node_modules\jake\lib\utils\index.js:124:9)
(See full trace by running task with --trace)
```

```
"gulp-imagemin": "2.2.1",
```

Do you have any idea why?

**Comment by kevva** [comment]
Some errors probably occurred upon `npm install` that you might have missed. However this is not an issue with this module but rather https://github.com/imagemin/gifsicle-bin. Try reinstalling and pay attention to the output.

**Comment by kud** [comment]
Okay, thank you. ;)
