### ISSUE TITLE
Install fails for png on windows 8.1 node 0.12.2

### ISSUE THREAD

**Issue by Karnith** [sindresorhus/gulp-imagemin#107]
here is the output:
```

E:\JMediaFrontend>npm remove gulp-imagemin
unbuild gulp-imagemin@1.2.1

E:\JMediaFrontend>npm install gulp-imagemin --msvs_version=2013
-
> jpegtran-bin@2.0.2 postinstall E:\JMediaFrontend\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemi
n-jpegtran\node_modules\jpegtran-bin
> node lib/install.js

  √ jpegtran pre-build test passed successfully

> pngquant-bin@3.0.0 postinstall E:\JMediaFrontend\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemi
n-pngquant\node_modules\pngquant-bin
> node lib/install.js

  √ pngquant pre-build test passed successfully

> optipng-bin@2.0.4 postinstall E:\JMediaFrontend\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin
-optipng\node_modules\optipng-bin
> node lib/install.js

  ‼ EPERM, symlink 'E:\JMediaFrontend\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\nod
e_modules\optipng-bin\vendor\optipng.exe'
  ‼ optipng pre-build test failed
  i compiling from source
  x Error: ./configure --with-system-zlib --prefix="E:\JMediaFrontend\node_modules\gulp-imagemin\node_modules\imagemin\n
ode_modules\imagemin-optipng\node_modules\optipng-bin\vendor" --bindir="E:\JMediaFrontend\node_modules\gulp-imagemin\nod
e_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor" && make install
Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --with-system-zlib --prefix="E:\JMediaFrontend\node_modul
es\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor" --bindir="E:\JMedi
aFrontend\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor
""
'.' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

> gifsicle@2.0.1 postinstall E:\JMediaFrontend\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-gi
fsicle\node_modules\gifsicle
> node lib/install.js

  √ gifsicle pre-build test passed successfully

gulp-imagemin@1.2.1 node_modules\gulp-imagemin
├── object-assign@1.0.0
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── through2-concurrent@0.3.1 (through2@0.6.5)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.1.0)
└── imagemin@2.2.1 (get-stdin@3.0.2, optional@0.1.3, vinyl@0.4.6, stream-combiner@0.2.1, through2@0.6.5, meow@2.1.0, con
cat-stream@1.4.8, vinyl-fs@0.3.13, imagemin-svgo@3.0.3, imagemin-jpegtran@4.1.0, imagemin-pngquant@4.1.0, imagemin-optip
ng@4.2.0, imagemin-gifsicle@4.1.0)
```

**Comment by kevva** [comment]
You have a global install of optipng somwhere. Due to permissions you aren't able to symlink it to the correct destinatiton. I'd suggest you remove it.

**Comment by Karnith** [comment]
I don't have optipng install globally. I am on windows, not linux/unix so symlink won't create a link. The compile then fails, probably because autoconfigure isn't installed correctly in windows. I'm checking that now.

**Comment by kevva** [comment]
`‼ EPERM, symlink`, it only tries to symlink when you have a global `optipng`. This will be fixed in the upcoming version though.

**Comment by localhosted** [comment]
I have a similar issue: 

```
Module build failed: Error: '"C:\Projects\demo1\node_modules\pngquant-bin\vendor\pngquant.exe"' is not recognized as an internal or external command,
operable program or batch file.
```

I don't have a global `optipng`
