### ISSUE TITLE
gulp-imagemin errors when piping to dest

### ISSUE THREAD

**Issue by heldinz** [sindresorhus/gulp-imagemin#122]
I have gulp-imagemin v2.3.0, gulp v3.9.0, and node v0.12.4 installed.

My gulp-imagemin task fails when it tries to pipe to dest. The output from the plugin itself says that gulp-imagemin worked fine, but the writing fails. When I tried imagemin-cli (v1.0.0) on the same file, it also worked without problems.

```
me:~/MyProject [master *]$ ./gulp images
[18:09:37] Using gulpfile ~/MyProject/gulpfile.js
[18:09:37] Starting 'images'...
[18:09:37] 'images' errored after 7.7 ms
[18:09:37] TypeError: undefined is not a function
    at DestroyableTransform.Readable.pipe (/Users/me/MyProject/node_modules/gulp-imagemin/node_modules/through2-concurrent/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:529:8)
    at Gulp.<anonymous> (/Users/me/MyProject/build/tasks/images.js:12:10)
    at module.exports (/Users/me/MyProject/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/me/MyProject/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/me/MyProject/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/me/MyProject/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/me/MyProject/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
[18:09:38] gulp-imagemin: Minified 1 image (saved 22.12 kB - 40%)
```

Line 12:10 in my images.js task is the line `.pipe(config.dest)`:
```
var gulp     = require('gulp'),
    imagemin = require('gulp-imagemin'),
    pngquant = require('imagemin-pngquant'),
    config   = require('../config').images;

gulp.task('images', function () {
    return gulp.src(config.src)
        .pipe(imagemin({
            progressive: true,
            use:         [pngquant()]
        }))
        .pipe(config.dest);
});
```

Any ideas as to why this is failing?

**Comment by sindresorhus** [comment]
> at Gulp.<anonymous> (/Users/me/MyProject/build/tasks/images.js:12:10)

I don't know how you `config` looks like, but `.pipe(config.dest);` should most likely be `.pipe(gulp.dest(config.dest));`

**Comment by heldinz** [comment]
/facepalm

Well that's embarrassing... Thanks for pointing it out!
