### ISSUE TITLE
TypeError: listener must be a function

### ISSUE THREAD

**Issue by ezequieltejada** [sindresorhus/gulp-imagemin#131]
Hi!

Just installed gulp-imagemin and I got this error

```
[01:27:55] TypeError: listener must be a function
    at TypeError (<anonymous>)
    at DestroyableTransform.EventEmitter.addListener (events.js:130:11)
    at DestroyableTransform.Readable.on (/var/www/public/node_modules/gulp-imagemin/node_modules/through2-concurrent/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:705:33)
    at Gulp.gulp.task.gulp.src.pipe.$.htmlReplace.logo.src (/var/www/public/gulpfile.js:123:13)
    at module.exports (/var/www/public/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/public/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/public/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/var/www/public/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:415:13)
```

this is the task I run:

```
gulp.task('build-images', function(){
    return gulp.src('app/assets/src/**/*.+(png|jpg|gif|jpeg)')
        .pipe($.debug({title:'BEFORE'}))
        .pipe(imagemin({
            progressive: true,
            svgoPlugins: [{removeViewBox: false}],
            use: [pngquant()]
        })).on('error', $.util.log({showStack:true}))
        .pipe($.debug({title:'AFTER'}))
        .pipe(gulp.dest('dest/images'));
});
```

Any ideas on why this is happening?

**Comment by shinnn** [comment]
```
$ node -e "console.log(typeof require('gulp-util').log('This snippet tells you the answer.'))"
```

**Comment by shinnn** [comment]
`require('gulp-util').log` does not return a function.

===========================

This is not gulp-imagemin-specific problem. You'll encounter this problem even if you replace `gulp-imagemin` with any other gulp plugin.

You shouldn't open issues related to this kind of error here. Use [StackOverflow](https://stackoverflow.com/).
