### ISSUE TITLE
TypeError: listener must be a function

### ISSUE THREAD

**Issue by ezequieltejada** [sindresorhus/gulp-imagemin#132]
Hi!

Trying to optimize some images I'm getting this error:

```
TypeError: listener must be a function
    at TypeError (<anonymous>)
    at DestroyableTransform.EventEmitter.addListener (events.js:130:11)
    at DestroyableTransform.Readable.on (/var/www/public/node_modules/gulp-imagemin/node_modules/through2-concurrent/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:705:33)
    at Gulp.gulp.task.gulp.src.pipe.$.htmlReplace.logo.src (/var/www/public/gulpfile.js:130:13)
    at module.exports (/var/www/public/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/public/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/public/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/var/www/public/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:415:13)
```

Do you know why I'm getting this error?

**Comment by shinnn** [comment]
Duplicate: #131
