### ISSUE TITLE
Throwing error

### ISSUE THREAD

**Issue by vdecree** [sindresorhus/gulp-imagemin#134]
My projects have been working absolutely fine, with no problems until tonight when I'm getting this error thrown:

```
C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\lib\svgo\plugins.js:46
        items.content = items.content.filter(function(item) {
                                     ^
TypeError: Cannot read property 'filter' of undefined
    at monkeys (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\lib\svgo\plugins.js:46:38)
    at perItem (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\lib\svgo\plugins.js:77:12)
    at C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\lib\svgo\plugins.js:18:24
    at Array.forEach (native)
    at module.exports (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\lib\svgo\plugins.js:14:13)
    at C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\lib\svgo.js:63:17
    at Object.sax.onend (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\lib\svgo\svg2js.js:140:26)
    at emit (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\node_modules\sax\lib\sax.js:625:33)
    at end (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\node_modules\sax\lib\sax.js:667:3)
    at Object.write (C:\Users\mathew\Documents\Work\builds\www\projectname\node_modules\gulp-svgmin\node_modules\svgo\node_modules\sax\lib\sax.js:929:30)
```

Any ideas?

**Comment by shinnn** [comment]
Please read the stack trace carefully. It's not a gulp-imagemin problem.
