### ISSUE TITLE
Able to compress jpg images except for the below image

### ISSUE THREAD

**Issue by dpburgess** [sindresorhus/gulp-imagemin#142]
![pizzeria](https://cloud.githubusercontent.com/assets/8584904/10412024/fa38bdd6-6f46-11e5-98e8-219df12c5e6e.jpg)

The console error output states:
events.js:85 throw er; //Unhandled 'error' event

Error: Error: write EOF
    at ChildProcess.<anonymous> (FILEPATH\imagemin-jpegtran\index.js:60:11)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

I didn't see anything else online about issues with .jpg files.

**Comment by shinnn** [comment]
> I didn't see anything else online about issues with .jpg files.

https://github.com/imagemin/imagemin-jpegtran/issues/8
