### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zwhitchcox** [sindresorhus/gulp-imagemin#145]
My error: 

```shell
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/zane/narkjs/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

My code: 

```js
 35 gulp.task('images', ['clean'], function() {
 36   return gulp.src(paths.images)
 37     .pipe(imagemin({optimizationLevel:5}))
 38     .pipe(debug())         
 39     .pipe(gulp.dest('build'))
 40 })

```

**Comment by shinnn** [comment]
https://github.com/sindresorhus/gulp-imagemin/issues/125#issuecomment-149851999
