### ISSUE TITLE
Broken plugin

### ISSUE THREAD

**Issue by dopesong** [sindresorhus/gulp-imagemin#161]
I get this when trying to minify:

```
/var/www/test/node_modules/gulp-imagemin/node_modules/gulp-util/lib/PluginError.js:73
  if (!this.message) throw new Error('Missing error message');
                     ^

Error: Missing error message
    at new PluginError (/var/www/test/node_modules/gulp-imagemin/node_modules/gulp-util/lib/PluginError.js:73:28)
    at DuplexWrapper.<anonymous> (/var/www/test/node_modules/gulp-imagemin/index.js:58:8)
    at emitOne (events.js:77:13)
    at DuplexWrapper.emit (events.js:169:7)
    at Through2.<anonymous> (/var/www/test/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:49:12)
    at emitOne (events.js:82:20)
    at Through2.emit (events.js:169:7)
    at onwriteError (/var/www/test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:347:10)
    at onwrite (/var/www/test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:365:5)
    at WritableState.onwrite (/var/www/test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:124:5)
```

This happened after npm update:

```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN unmet dependency /var/www/test/node_modules/gulp/node_modules/vinyl-fs requires through2@'^0.6.1' but will load
npm WARN unmet dependency /var/www/test/node_modules/through2,
npm WARN unmet dependency which is version 2.0.1
```

**Comment by RicardoRodrigues** [comment]
I have same problem... but not have `stream-combiner2`.

**Comment by witoldszpur** [comment]
same in my case.

**Comment by emanuelis** [comment]
+1

**Comment by shinnn** [comment]
@dopesong @RicardoRodrigues @witoldszpur @emanuelis Can you create a smallest possible repository by which we can reproduce the error?

**Comment by witoldszpur** [comment]
in my case is impossible is very big commercial project. For sure is gulp-imagemin problem. Maybe I should use npm-shrinkwrap ?

**Comment by shinnn** [comment]
@witoldszpur No need to open-source your entire project. The repository should include just one package.json, one gulpfile and one image file then we can investigate the root cause.

> For sure is gulp-imagemin problem. 

If you've already confirmed which part of the code is causing problems, please submit a pull request to fix it.

**Comment by witoldszpur** [comment]
@shinnn 

```javascript
gulp.task('imagemin', function() {
  return gulp.src([paths.IMAGES + '/**/*.*(jpg|jpeg|png|gif|svg)'], { cwd: './' })
    .pipe(imagemin({
      progressive: true,
      use: [
        imageminPngquant({
          quality: '60-90',
          speed: 1
        })
      ]
    }))
    .pipe(gulp.dest(paths.DIST + '/assets/images'))
    .pipe(notify({
      message: 'Imagemin task complete: <%= file.relative %>',
      onLast: true
    }));
});
``` 
This task crashed build. In our case we use Jenkins to release. Each time when we release, task clean npm_modules - that mean something changed in dep within 3-4 days. That mean gulp-imagemin or imagemin have something wrong in dep. What is weird, in Win or Mac don't work but in linux somehow works.

**Comment by shinnn** [comment]
Confirmed. This is a imagemin-pngquant bug. This discussion continues to https://github.com/imagemin/imagemin-pngquant/issues/21.

@witoldszpur Thanks for the clarification.

**Comment by RicardoRodrigues** [comment]
Thanks seemed to solve. :+1:
