### ISSUE TITLE
gifsicle ENOENT error when attempting to npm install gulp-imagemin on Ubuntu 14.04

### ISSUE THREAD

**Issue by john-doherty** [sindresorhus/gulp-imagemin#164]
I get the following error when attempting to do gulp build due to the ```gulp-imagemin``` module. I'm using node v5.10.1 and npm v2.12.1. I have tried everything I can think of including sudo npm install gulp-imagemin but keep getting the same error: 

```js
/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by sindresorhus** [comment]
The error is coming from https://github.com/imagemin/gifsicle-bin. Open an issue there.
