### ISSUE TITLE
TypeError: stream.on is not a function

### ISSUE THREAD

**Issue by kilianc** [sindresorhus/gulp-imagemin#167]
Node `5.10.1` and `5.11.0`. gulp-imagemin `2.4.0` imagemin-pngquant `5.0.0`

````
/website/node_modules/readable-stream/lib/_stream_readable.js:740
  stream.on('end', function () {
         ^

TypeError: stream.on is not a function
    at Readable.wrap (/website/node_modules/readable-stream/lib/_stream_readable.js:740:10)
    at wrap (/website/node_modules/stream-combiner2/index.js:67:29)
    at combine (/website/node_modules/stream-combiner2/index.js:29:18)
    at Function.module.exports.obj (/website/node_modules/stream-combiner2/index.js:22:10)
    at Imagemin.createStream (/website/node_modules/imagemin/index.js:103:24)
    at Imagemin.run (/website/node_modules/imagemin/index.js:77:20)
    at DestroyableTransform.through.obj.percent (/website/node_modules/gulp-imagemin/index.js:56:12)
    at DestroyableTransform._transform (/website/node_modules/through2-concurrent/through2-concurrent.js:29:15)
    at DestroyableTransform.Transform._read (/website/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/website/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)

**Comment by kilianc** [comment]
P.S. on OSX works I have this issue inside an Ubuntu container. I updated the deps today and it started failing.

**Comment by shinnn** [comment]
https://github.com/imagemin/imagemin/issues/165

Please read at least the top of README before opening new issues.

**Comment by kilianc** [comment]
@shinnn I don't know why you assume I didn't read it but it's clear me opening issues is bothering you for some reason.

The link you posted doesn't offer any info or resolution to the problem other than saying that the API changed.

> This is most likely due to you using the wrong version of a custom plugin. We migrated away from streams to promises last week. Make sure you're using the correct version of your plugin.

I listed in my issue the versions I am using, I am still trying to figure this out.

Also, I am not sure what this means

> Issues with the output should be reported on the imagemin issue tracker.

because to me that doesn't seem like an error with the output image, but an exception thrown using the code example in this very repository.

**Comment by kevva** [comment]
@kilianc, use `imagemin-pngquant@4`.

**Comment by kilianc** [comment]
@kevva I would consider adding this to the readme and updating the code example that literally says to install latest

```js
const pngquant = require('imagemin-pngquant'); // $ npm i -D imagemin-pngquant
```

**Comment by shinnn** [comment]
@kilianc Ah, sorry I thought https://github.com/sindresorhus/gulp-imagemin/pull/166 has been already merged.

**Comment by Code-Stars** [comment]
I got this error because I used the node modules 'rename' package while I needed the 'gulp-rename' package.
