### ISSUE TITLE
Build issue with v3.0.0 

### ISSUE THREAD

**Issue by outaTiME** [sindresorhus/gulp-imagemin#171]
Install, fails ... check out the stdout:

```
> optipng-bin@3.1.1 postinstall /Users/outaTiME/Code/outa.im/node_modules/gulp-imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> gifsicle@3.0.3 postinstall /Users/outaTiME/Code/outa.im/node_modules/gulp-imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> mozjpeg@4.1.1 postinstall /Users/outaTiME/Code/outa.im/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/Users/outaTiME/Code/outa.im/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Users/outaTiME/Code/outa.im/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --bindir="/Users/outaTiME/Code/outa.im/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" --libdir="/Users/outaTiME/Code/outa.im/node_modules/gulp-imagemin/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor" && make --jobs=4 && make install --jobs=4
Command failed: /bin/sh -c autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
configure.ac:22: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by shinnn** [comment]
This is not an issue with this plugin but with `mozjpeg` module.

**Comment by outaTiME** [comment]
ok but the previous version not use mozjpeg dependency and it works

**Comment by outaTiME** [comment]
for now im using previous release

**Comment by shinnn** [comment]
http://www.catb.org/esr/faqs/smart-questions.html#forum

**Comment by outaTiME** [comment]
ok, understood but ... something wrong with jpg check out #170 issue

**Comment by shinnn** [comment]
If you want others to hear what you say, you should hear what others say first. You thoughtlessly begins the comment with "ok" but you actually don't read my advice.
