### ISSUE TITLE
Mozjpeg Cannot Compile :(

### ISSUE THREAD

**Issue by mike3run** [sindresorhus/gulp-imagemin#175]
Hey there I've used this plugin for a long time no problems but yesterday I was installing it and got this error:

```
⚠ The `/Users/AirMike/Documents/git/ground-zero/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Users/AirMike/Documents/git/ground-zero/node_modules/mozjpeg/vendor" --bindir="/Users/AirMike/Documents/git/ground-zero/node_modules/mozjpeg/vendor" --libdir="/Users/AirMike/Documents/git/ground-zero/node_modules/mozjpeg/vendor" && make --jobs=4 && make install --jobs=4
Command failed: ./configure --disable-shared --prefix="/Users/AirMike/Documents/git/ground-zero/node_modules/mozjpeg/vendor" --bindir="/Users/AirMike/Documents/git/ground-zero/node_modules/mozjpeg/vendor" --libdir="/Users/AirMike/Documents/git/ground-zero/node_modules/mozjpeg/vendor"
configure: error: installation or configuration problem: assembler cannot create object files.

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by mike3run** [comment]
I've already tried to reinstall several times with no luck even running 
`node node_modules/mozjpeg/lib/install.js`

To install that part manually but nothing :(

**Comment by mike3run** [comment]
https://github.com/imagemin/imagemin/issues/168

**Comment by shinnn** [comment]
Yes, new comments should go to https://github.com/imagemin/imagemin/issues/168 instead.
