### ISSUE TITLE
Error "const path" SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by napcat** [sindresorhus/gulp-imagemin#178]
I update to version 3.0.0 and I'm getting this error:

```
D:\project\node_modules\gulp-imagemin\index.js:2
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\project\gulpfile.js:87:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by SamVerschueren** [comment]
Upgrade your node version.

**Comment by napcat** [comment]
I'm currently using node version 5.4.1.

Can I update to a 5.x version or do I need to update to 6.x?

**Comment by SamVerschueren** [comment]
Are you sure you are on node 5.x (`node -v`)? As long as you are on node >=4, you should be good to go.

http://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode

**Comment by napcat** [comment]
I was on 4.4.2LTS and update to 5.4.1 a fews weeks ago.
In the cmd:

C:\>node -v
v5.4.1

C:\>npm -v
3.5.3

**Comment by shinnn** [comment]
@napcat Add this code snippet to the top of your gulpfile:

```js
console.log('Node version: ' + process.version);
```

then please show us the result.

**Comment by jaycom** [comment]
I updated the lib, and get this issues too,
Then I reinstall the nodejs version 4.4.4 and npm 3.8.9
it's work.

**Comment by shinnn** [comment]
@napcat Any feedback?

**Comment by napcat** [comment]
Yes, I think I found the solution..
If I run the command in the cmd there's no error and the version logs correctly.
Here is the full log:

`D:\project\>gulp build
**Node version: v5.4.1**
[10:19:43] Using gulpfile D:\project\gulpfile.js
[10:19:43] Starting 'build'...
[10:19:43] Starting 'clean'...
[10:19:43] Finished 'clean' after 22 ms
[10:19:43] Starting 'html'...
[10:19:43] Finished 'html' after 1.45 ms
[10:19:43] Starting 'assets'...
[10:19:43] Finished 'assets' after 3.7 ms
[10:19:43] Starting 'js'...
[10:19:43] Finished 'js' after
[10:19:43] Finished 'build' after
[10:19:51] gulp-imagemin: Minified 2 images (saved 3.59 kB - 2.3%)`

But in using Visual Studio 2015. In Visual Studio 2015 there's a UI to run the gulp tasks, the "Task Runner Explorer". The exact same gulpfile breaks the task runner in VS with the following output:

`Failed to run "D:\project\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
D:\project\node_modules\gulp-imagemin\index.js:2
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\project\gulpfile.js:86:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)`

I searched a bit and with your help, I found out that VS installs an old node version and probably VS was using it. I had to go to Tools > Options > Projects and Solutions > External Web Tools and add the current nodejs path "C:\Program Files\nodejs".

It's working know. Thank you for the help, and sorry for the trouble...

**Comment by boardgames** [comment]
Ubuntu

nodejs -v
v6.9.4

npm -v
3.10.10

node_modules/gulp-eslint/index.js:3
const BufferStreams = require('bufferstreams');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/bitnami/mobicon/app/controllers/projects/projects.lint.server.controller.js:8:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/bitnami/mobicon/app/controllers/projects.server.controller.js:15:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/bitnami/mobicon/app/routes/projects.server.routes.js:7:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

Any idea?

**Comment by benrondeau** [comment]
If someone is running the 'Task Runner' tool in Visual Studio (I am using 2017 but should be true in previous versions), it ships with an old version of node which doesn't support ES6. Turning off this version of node to run gulp tasks solves this issue:

![vscode-toolbox](https://user-images.githubusercontent.com/5001219/29138204-881b7118-7d08-11e7-9b25-c22c2d5686b5.PNG)

This menu can be found here: `Tools > Options > Projects and Solutions > Web Package Management > External Web Tools` and DESELECT the option for `$(VSINSTALLDIR)\Web\External`
