### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by RehanSaeed** [sindresorhus/gulp-imagemin#182]
I get this error using the latest 3.0.1 release. Also, are there any breaking changes, why was the major version changed?

```
Failed to run "C:\Test\WebApplication20\WebApplication20\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
C:\Test\WebApplication20\WebApplication20\node_modules\gulp-imagemin\index.js:2
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by shinnn** [comment]
https://github.com/sindresorhus/gulp-imagemin/issues/181#issuecomment-219303510
