### ISSUE TITLE
gulp-imagemin with gulp-cache - Unhandled rejection TypeError: Cannot read property 'kill' of undefined

### ISSUE THREAD

**Issue by crocodileDundee** [sindresorhus/gulp-imagemin#187]
I'm running `gulp-imagemin` with `gulp-cache`, like this:

```javascript
// gulpfile.js
var
  cache    = require('gulp-cache'),
  imagemin = require('gulp-imagemin')

gulp.task('img', function() {
  gulp
    .src('./img/**')
    .pipe(cache(imagemin()))
    .pipe(gulp.dest('./site/img/'));
});
```
If I run it with like this (with `gulp-cache`), I get this error:
```bash
$ gulp img
[21:26:36] Using gulpfile ./gulpfile.js
[21:26:36] Starting 'img'...
[21:26:36] Finished 'img' after 10 ms
Unhandled rejection TypeError: Cannot read property 'kill' of undefined
    at module.exports (./node_modules/gulp-imagemin/node_modules/imagemin-jpegtran/node_modules/exec-buffer/node_modules/execa/index.js:80:24)
    at ./node_modules/gulp-imagemin/node_modules/imagemin-jpegtran/node_modules/exec-buffer/index.js:31:15
```

If I remove the `cache` though,
```javascript
// gulpfile.js
gulp.task('img', function() {
  gulp
    .src('./img/**')
    .pipe(imagemin())
    .pipe(gulp.dest('./site/img/'));
});
```

It works:
```bash
$ gulp img
[21:36:09] Using gulpfile ./gulpfile.js
[21:36:09] Starting 'img'...
[21:36:09] Finished 'img' after 8.97 ms
```

What do I have to change or add to make `gulp-imagemin` work with `gulp-cache`?

**Comment by jlengstorf** [comment]
I think this may be related to the fix I listed here: https://github.com/sindresorhus/gulp-imagemin/issues/173#issuecomment-230737023

**Comment by shinnn** [comment]
Thanks, @jlengstorf. Probably https://github.com/sindresorhus/gulp-imagemin/issues/173#issuecomment-230737023 is the answer.
