### ISSUE TITLE
Install Fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by erwstout** [sindresorhus/gulp-imagemin#189]
I'm not sure if I should post this here or on imagemin's repo, but when I try to install using `npm install --save-dev gulp-imagemin` I get the following errors:

```
> optipng-bin@3.1.2 postinstall /media/ericstout/Storage/git/imagemin-test/node_modules/optipng-bin
> node lib/install.js

  ⚠ Couldn't execute the `/media/ericstout/Storage/git/imagemin-test/node_modules/optipng-bin/vendor/optipng` binary. Make sure it has the right permissions.
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✔ optipng built successfully

> jpegtran-bin@3.0.6 postinstall /media/ericstout/Storage/git/imagemin-test/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ Couldn't execute the `/media/ericstout/Storage/git/imagemin-test/node_modules/jpegtran-bin/vendor/jpegtran` binary. Make sure it has the right permissions.
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: touch configure.ac aclocal.m4 configure Makefile.am Makefile.in && ./configure --disable-shared --prefix="/media/ericstout/Storage/git/imagemin-test/node_modules/jpegtran-bin/vendor" --bindir="/media/ericstout/Storage/git/imagemin-test/node_modules/jpegtran-bin/vendor" && make install
Command failed: ./configure --disable-shared --prefix="/media/ericstout/Storage/git/imagemin-test/node_modules/jpegtran-bin/vendor" --bindir="/media/ericstout/Storage/git/imagemin-test/node_modules/jpegtran-bin/vendor"
configure: error: no nasm (Netwide Assembler) found

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

> gifsicle@3.0.3 postinstall /media/ericstout/Storage/git/imagemin-test/node_modules/gifsicle
> node lib/install.js

  ⚠ Couldn't execute the `/media/ericstout/Storage/git/imagemin-test/node_modules/gifsicle/vendor/gifsicle` binary. Make sure it has the right permissions.
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="/media/ericstout/Storage/git/imagemin-test/node_modules/gifsicle/vendor" --bindir="/media/ericstout/Storage/git/imagemin-test/node_modules/gifsicle/vendor" && make install
Command failed: autoreconf -ivf
/bin/sh: 1: autoreconf: not found

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)

```

Any thoughts? I see it is throwing a few permission errors but using `sudo` doesn't work and obviously isn't recommended.

EDIT: I just installed imagemin alone, and get no errors at all.

**Comment by kevva** [comment]
Install `nasm` and `autoconf`.

**Comment by erwstout** [comment]
Still having the same problems... On install:

```
"/media/ericstout/Storage/git/prelude-test/node_modules/node-sass/vendor/linux-x64-48/binding.node" exists. 
 testing binary.
Binary is fine; exiting.

> pngquant-bin@3.1.0 postinstall /media/ericstout/Storage/git/prelude-test/node_modules/pngquant-bin
> node lib/install.js

  ⚠ Couldn't execute the `/media/ericstout/Storage/git/prelude-test/node_modules/pngquant-bin/vendor/pngquant` binary. Make sure it has the right permissions.
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

> optipng-bin@3.1.2 postinstall /media/ericstout/Storage/git/prelude-test/node_modules/optipng-bin
> node lib/install.js

  ⚠ Couldn't execute the `/media/ericstout/Storage/git/prelude-test/node_modules/optipng-bin/vendor/optipng` binary. Make sure it has the right permissions.
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✔ optipng built successfully

> jpegtran-bin@3.0.6 postinstall /media/ericstout/Storage/git/prelude-test/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ Couldn't execute the `/media/ericstout/Storage/git/prelude-test/node_modules/jpegtran-bin/vendor/jpegtran` binary. Make sure it has the right permissions.
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✔ jpegtran built successfully

> gifsicle@3.0.3 postinstall /media/ericstout/Storage/git/prelude-test/node_modules/gifsicle
> node lib/install.js

  ⚠ Couldn't execute the `/media/ericstout/Storage/git/prelude-test/node_modules/gifsicle/vendor/gifsicle` binary. Make sure it has the right permissions.
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✔ gifsicle built successfully
```
And when trying to run the task (minify images):

```
[17:58:27] Starting 'images'...
internal/child_process.js:302
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:949:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:367:9)
    at Through2._transform (/media/ericstout/Storage/git/prelude-test/node_modules/imagemin-jpegtran/index.js:40:12)
    at Through2.Transform._read (/media/ericstout/Storage/git/prelude-test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Through2.Transform._write (/media/ericstout/Storage/git/prelude-test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/media/ericstout/Storage/git/prelude-test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/media/ericstout/Storage/git/prelude-test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at Through2.Writable.write (/media/ericstout/Storage/git/prelude-test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/media/ericstout/Storage/git/prelude-test/node_modules/imagemin-gifsicle/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```

**Comment by miguelsmuller** [comment]
you can solve this problem @erwstout ?
I'm going through the same difficulty
