### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by chrisdemars** [sindresorhus/gulp-imagemin#208]
I added gulp-imagemin to my package.json file and ran an npm install and this is the error I keep getting.

```
Error: Cannot find module 'gulp-imagemin'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/chrisdemars/Projects/bulp/gulpfile.js:11:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```
Than when I try and install gulp-imagemin again, I get this error.

```
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
```
How can I fix this to get gulp-imagemin to work?

**Comment by sindresorhus** [comment]
Probably something went wrong during `npm install`. Use https://github.com/npm/npm/issues for npm support.

> Than when I try and install gulp-imagemin again, I get this error.

That's a warning, not an error, and has no impact on whether it works or not.
