### ISSUE TITLE
events.js:141 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by iminif** [sindresorhus/gulp-imagemin#211]
1) Command and errors:
> gulp
[23:47:07] Using gulpfile D:\path\to\myWorkDir\gulpfile.js
[23:47:07] Starting 'default'...
[23:47:07] Finished 'default' after 8.87 ms

events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: The system cannot find the path specified.

    at notFoundError (D:\path\to\myWorkDir\node_modules\cross-spawn-async\lib\enoent.js:8:11)
    at verifyENOENT (D:\path\to\myWorkDir\node_modules\cross-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (D:\path\to\myWorkDir\node_modules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

2) Content of my gulpfile.js
const gulp = require('gulp')
const imagemin = require('gulp-imagemin')

gulp.task('default', function()
{
    gulp.src('src/img/*')
        .pipe(imagemin())
        .pipe(gulp.dest('dist/img'))
})

**Comment by kevva** [comment]
What version are you running? This is most likely due to some `imagemin` plugin failing to install.

**Comment by iminif** [comment]
So, as you have said, I re-install all packages then the problem have gone. thank you!

**Comment by youngyyy** [comment]
I have re-installed all packages,but this problem still exist and the tips are messy。

`errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn undefined',
  killed: false,
  stdout: '',
  stderr: 'ϵͳ�Ҳ���ָ����·����\r\n',
  failed: true,
  signal: null, 
 stack: 'Error: ϵͳ�Ҳ���ָ����·����\r\n\n    at notFoundError `
