### ISSUE TITLE
Error: write EPIPE 

### ISSUE THREAD

**Issue by GJ2511** [sindresorhus/gulp-imagemin#223]
Hi I am getting following error in MAC and Window Env but working fine in UBUNTU

```
 events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:795:14)
```

My Gulp task is :-

```

const image = require('gulp-imagemin')
gulp.task('build-image', ['build-copy'], () => {
        gulp.src(INPUT_SRC)
            .pipe(image())
            .pipe(gulp.dest(DESTINATION));
});
```

**Comment by sindresorhus** [comment]
@kevva We should improve the error message when a binary is missing or not working.

**Comment by antgonzales** [comment]
@GJ2511 how did you solve the issue?
