### ISSUE TITLE
On build Unhandled 'error' event Error EONENT

### ISSUE THREAD

**Issue by KixS** [sindresorhus/gulp-imagemin#225]
Hi,

I have an issue when trying to use imagemin when building on gulp.

Here is my code:
```
gulp.task('imagemin', ['clean'], function() {
gulp.src(paths.images)
.pipe(imagemin())
.pipe(gulp.dest(paths.dist + 'img'));
});
```

My environment:
node: 5.12.0
imagemin: 3.0.3

I have tried both with jpg and png images and both give issues:
```
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/ismail/Documents/talirapp/myTalirConsumer/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:893:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
```
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/ismail/Documents/talirapp/myTalirConsumer/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:893:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I have tried unsinstalling and reinstalling imagemin, I have tried with several versions of node going back to 4.6.0. but no configurations worked.
When I go back to node 0.12.16, I get the error referenced in #181

Any idea ?

**Comment by KixS** [comment]
I found the issue. It was coming from the plugins used.

I deleted the folders manually from myProjects/nodes_modules

*optipng
*jpegtran

and then reinstalled these plugins
