### ISSUE TITLE
3.1.0 breaks svgo

### ISSUE THREAD

**Issue by andrenarchy** [sindresorhus/gulp-imagemin#229]
With 3.0.3 the following code worked:

```
  gulp.src(paths.staticFiles)
    .pipe(imagemin([
      imagemin.jpegtran(),
      imagemin.optipng(),
      imagemin.svgo({plugins: [{removeViewBox: false}, {minifyStyles: false}]}),
    ], {verbose: true}))
    .pipe(gulp.dest(buildDir + '/static'));
```

With 3.1.0 the svgo plugin fails:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
CssSyntaxError: Colon is expected
    at parseError (/home/andre/git-repos/paperhive-frontend/node_modules/csso/lib/parser/index.js:46:17)
    at eat (/home/andre/git-repos/paperhive-frontend/node_modules/csso/lib/parser/index.js:82:5)
    at getDeclaration (/home/andre/git-repos/paperhive-frontend/node_modules/csso/lib/parser/index.js:538:5)
    at getDeclarations (/home/andre/git-repos/paperhive-frontend/node_modules/csso/lib/parser/index.js:499:25)
    at Object.getBlock [as block] (/home/andre/git-repos/paperhive-frontend/node_modules/csso/lib/parser/index.js:529:23)
    at parse (/home/andre/git-repos/paperhive-frontend/node_modules/csso/lib/parser/index.js:1857:34)
    at minify (/home/andre/git-repos/paperhive-frontend/node_modules/csso/lib/index.js:71:9)
    at Object.minifyBlock (/home/andre/git-repos/paperhive-frontend/node_modules/csso/lib/index.js:106:12)
    at Object.exports.fn (/home/andre/git-repos/paperhive-frontend/node_modules/svgo/plugins/minifyStyles.js:38:42)
    at /home/andre/git-repos/paperhive-frontend/node_modules/svgo/lib/svgo/plugins.js:59:45
```

Did the options handling change? (note: it shouldn't run the minifystyles code)

**Comment by andrenarchy** [comment]
Quick update: I was able to work around this issue by instantiating the imagemin plugins manually, i.e.:

```
var imageminJpegtran = require('imagemin-jpegtran');
var imageminOptipng = require('imagemin-optipng');
var imageminSvgo = require('imagemin-svgo');

// ...
    .pipe(imagemin([
      imageminJpegtran(),
      imageminOptipng(),
      imageminSvgo({plugins: [{removeViewBox: false}, {minifyStyles: false}]}),
    ], {verbose: true}))
```

**Comment by sindresorhus** [comment]
// @zcei

**Comment by zcei** [comment]
Oh shit, I'm sorry. Currently you get an instance without parameters returned when you call the proxy function.

This is a regression, and I'll try to file a PR today to fix this, basically by forwarding all parameters to the instance creation. Does this sound okay?

@sindresorhus: for a major version increase I would recommend removing the export of optionalDependencies, and rather let them require needed plugins on their own in case they want to extend the default set.

**Comment by anuraag279** [comment]
+1

**Comment by sindresorhus** [comment]
> for a major version increase I would recommend removing the export of optionalDependencies, and rather let them require needed plugins on their own in case they want to extend the default set.

I've considered it many times, but I think it's nice to have a good default for people that wants something that just works without having to manually install many dependencies and do lots of config.
