### ISSUE TITLE
_gulpImagemin2.default.mozjpeg is not a function

### ISSUE THREAD

**Issue by yoanmalie** [sindresorhus/gulp-imagemin#255]
Hi
I moved to the new syntax of the release 3.0.0. But it appear that the jpeg compression won't work.
Here my task (i'm using Babel too) :

```js
gulp.task('images', () => {
    gulp.src(img.src + img.entry + '.{' + img.extensions + '}')
    .pipe(imagemin([
        imagemin.gifsicle({interlaced: true}),
        imagemin.mozjpeg({progressive: true}),
        imagemin.optipng({optimizationLevel: 3}),
        imagemin.svgo({
            plugins: [{
                removeViewBox: false,
                cleanupIDs: false,
            }]
        })
    ]))
    .pipe(gulp.dest(img.dest));
});

```

And here the error i have :

```sh
[11:49:43] Using gulpfile ~/Projets/gulp-static-starter/gulpfile.babel.js
[11:49:43] Starting 'images'...
[11:49:43] 'images' errored after 37 ms
[11:49:43] TypeError: _gulpImagemin2.default.mozjpeg is not a function
    at Gulp.<anonymous> (/home/yoan/Projets/gulp-static-starter/gulptasks/images.js:12:18)
    at module.exports (/home/yoan/Projets/gulp-static-starter/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/yoan/Projets/gulp-static-starter/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/yoan/Projets/gulp-static-starter/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/yoan/Projets/gulp-static-starter/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:46:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3
```

node 7.6.0
npm 4.3.0
gulp-imagemin 3.2.0
Running on Ubuntu 16.04

**Comment by sindresorhus** [comment]
`.mozjpeg` => `. jpegtran`

**Comment by yoanmalie** [comment]
@sindresorhus  Thank i saw this here : https://github.com/sindresorhus/gulp-imagemin/releases/tag/v3.0.0 
Can you update the description ?

**Comment by sindresorhus** [comment]
Done
