### ISSUE TITLE
Error using gulp-imagemin with node 7.10.0

### ISSUE THREAD

**Issue by gilbertosil** [sindresorhus/gulp-imagemin#269]
Hello, 
My configuration:
* Node: 7.10.0
* npm: 4.2.0
* gulp: 3.9.1
* gulp-cli: 1.3.0
* gulp-imagemin: 3.3.0

I created a simple task in my gulp file, the same basic use example, but when I run it, I get the message:

```
fs.js:961
  binding.lstat(pathModule._makeLong(path), statValues);


Error: ENOENT: no such file or directory, lstat 'imagemin'
    at Object.fs.lstatSync (fs.js:961:11)
    at renderFile (/usr/local/lib/node_modules/pug-cli/index.js:246:17)
    at /usr/local/lib/node_modules/pug-cli/index.js:149:5
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/pug-cli/index.js:148:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
Could you help me ?

**Comment by kevva** [comment]
This looks like an issue with `pug-cli`. Going to close and unless you can't provide some code that says otherwise it's not much we can do.
