### ISSUE TITLE
Not work at node@8.1.4

### ISSUE THREAD

**Issue by spursy** [sindresorhus/gulp-imagemin#272]
**my node env is @8.1.4**

My code is like,
```
gulp.task('image', (cb) => {
    console.log('12312' + (gulp instanceof EventEmitter))
    gulp.src('./src/image/*')
        .pipe(imageminify())
        .pipe(gulp.dest('./dist'))
})
```

when i process gulp image in CLI,  I get the followed exception:

![webwxgetmsgimg](https://user-images.githubusercontent.com/11460991/29129059-35a174e6-7d58-11e7-86c2-1ae8de1d5f05.jpeg)

**Comment by dcalhoun** [comment]
I'm not sure if this is the same exact issue, but I'm receiving the following error using node@8.6.0.

```
TypeError: Cannot read property 'setEncoding' of undefined
    at Through2._transform (/Users/username/Sites/web/project/node_modules/imagemin-jpegtran/index.js:6:11)
    at Through2.Transform._read (/Users/username/Sites/web/project/node_modules/readable-stream/lib/_stream_transform.js:6:10)
    at Through2.Transform._write (/Users/username/Sites/web/project/node_modules/readable-stream/lib/_stream_transform.js:6:1)
    at doWrite (/Users/username/Sites/web/project/node_modules/readable-stream/lib/_stream_writable.js:6:1)
    at writeOrBuffer (/Users/username/Sites/web/project/node_modules/readable-stream/lib/_stream_writable.js:6:3)
    at Through2.Writable.write (/Users/username/Sites/web/project/node_modules/readable-stream/lib/_stream_writable.js:6:11)
    at write (/Users/username/Sites/web/project/node_modules/imagemin-gifsicle/node_modules/readable-stream/lib/_stream_readable.js:6:20)
    at flow (/Users/username/Sites/web/project/node_modules/imagemin-gifsicle/node_modules/readable-stream/lib/_stream_readable.js:6:3)
    at /Users/username/Sites/web/project/node_modules/imagemin-gifsicle/node_modules/readable-stream/lib/_stream_readable.js:6:3
    at _combinedTickCallback (internal/process/next_tick.js:6:3)
    at process._tickDomainCallback (internal/process/next_tick.js:6:1)
```

### Environment
- node@8.6.0
- gulp-imagemin@2.4.0
- macOS 10.13

@sindresorhus would this error mean the file is not making it's way into `imagemin-jpegtran`?

**Comment by XhmikosR** [comment]
Does this still happen?
