### ISSUE TITLE
 Error: premature close

### ISSUE THREAD

**Issue by GabLeRoux** [sindresorhus/gulp-imagemin#278]
Hi, I'm getting the following error:
```
[15:49:11] Compressing and copying images
[15:49:11] ./src/lib/bootstrap-colorpicker/dist/img/**/*.*
[15:49:11] ./src/assets/images/**/*.*
[15:49:11] 'images' errored after 218 ms
[15:49:11] Error: premature close
    at DestroyableTransform.onclose (<snip>/node_modules/end-of-stream/index.js:35:54)
    at emitNone (events.js:110:20)
    at DestroyableTransform.emit (events.js:207:7)
    at <snip>/node_modules/vinyl-fs/node_modules/through2/through2.js:20:10
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

But it only happens to me, not my other team members. I tried with multiple node versions and always getting the same.

```bash
node --version
v8.6.0
npm --version
5.5.1
```

I was using `rvm`, but I'm now using [`n`](https://github.com/tj/n) and had troubles with rebuilding `node-sass`, but I don't think it's related. No matter the version or tool I used, I'm still getting this.

```bash
npm list --depth=0 | grep image
├── gulp-imagemin@2.4.0
```

I tried again with an updated version of `gulp-imagemin`:
```bash
npm list --depth=0 | grep image
├── gulp-imagemin@3.4.0
```

Same error (with same line numbers).

My `gulp` task:

```javascript
/**
 * Compress images
 * @return {Stream}
 */
gulp.task('images', ['clean-images'], function() {
    log('Compressing and copying images');
    var images = config.images,
        files = images.bower.map((lib) => config.bower.dir + lib + "**/*.*");
    files.push(config.src + images.dir + "**/*.*");
    log(files);

    return pump([
        gulp.src(files),
        $.imagemin({ optimizationLevel: 4 }),
        gulp.dest(config.temp + images.dir)
    ]);
});
```

**Comment by GabLeRoux** [comment]
I just tried the `imagemin-cli` command line and it worked for the same source folders.

**Comment by psavard** [comment]
Maybe you could use pipe to try to get more info on your problem

```javascript
    return gulp.src(files)
        .pipe($.imagemin({ optimizationLevel: 4 }))
        .on('error', function(e) { console.log(e); })
        .pipe(gulp.dest(config.temp + images.dir));
```

**Comment by GabLeRoux** [comment]
Managed to find more info with the above, thanks @psavard 🎉 

```
{ Error: spawn <project_path>/node_modules/optipng-bin/vendor/optipng ENOENT
    at _errnoException (util.js:1041:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn <project_path>/node_modules/optipng-bin/vendor/optipng',
  path: '<project_path>/node_modules/optipng-bin/vendor/optipng',
  spawnargs: 
   [ '-strip',
     'all',
     '-clobber',
     '-fix',
     '-o',
     3,
     '-out',
     '/private/var/folders/44/1h74hkj534j6b5cwsbkcsm200000gn/T/7a859847-51e5-414d-a022-d3b29d6228c3',
     '/private/var/folders/44/1h74hkj534j6b5cwsbkcsm200000gn/T/833f7926-7c3e-4697-b654-4801ee64c6c5' ],
  killed: false,
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd: '<project_path>/node_modules/optipng-bin/vendor/optipng -strip all -clobber -fix -o 3 -out /private/var/folders/44/1h74hkj534j6b5cwsbkcsm200000gn/T/7a859847-51e5-414d-a022-d3b29d6228c3 /private/var/folders/44/1h74hkj534j6b5cwsbkcsm200000gn/T/833f7926-7c3e-4697-b654-4801ee64c6c5',
  timedOut: false,
  name: 'Error',
  message: 'spawn <project_path>/node_modules/optipng-bin/vendor/optipng ENOENT',
  stack: 'Error: spawn <project_path>/node_modules/optipng-bin/vendor/optipng ENOENT\n    at _errnoException (util.js:1041:11)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)\n    at onErrorNT (internal/child_process.js:374:16)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',
  fileName: '<project_path>/src/lib/bootstrap-colorpicker/dist/img/bootstrap-colorpicker/alpha-horizontal.png',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-imagemin' }
{ Error: spawn <project_path>/node_modules/optipng-bin/vendor/optipng ENOENT
    at _errnoException (util.js:1041:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn <project_path>/node_modules/optipng-bin/vendor/optipng',
  path: '<project_path>/node_modules/optipng-bin/vendor/optipng',
  spawnargs: 
   [ '-strip',
     'all',
     '-clobber',
     '-fix',
     '-o',
     3,
     '-out',
     '/private/var/folders/44/1h74hkj534j6b5cwsbkcsm200000gn/T/e4e7283d-753d-4cae-a79c-47b0904f6912',
     '/private/var/folders/44/1h74hkj534j6b5cwsbkcsm200000gn/T/05ddb25a-e862-4ba9-b3c5-96867afb1b5f' ],
  killed: false,
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd: '<project_path>/node_modules/optipng-bin/vendor/optipng -strip all -clobber -fix -o 3 -out /private/var/folders/44/1h74hkj534j6b5cwsbkcsm200000gn/T/e4e7283d-753d-4cae-a79c-47b0904f6912 /private/var/folders/44/1h74hkj534j6b5cwsbkcsm200000gn/T/05ddb25a-e862-4ba9-b3c5-96867afb1b5f',
  timedOut: false,
  name: 'Error',
  message: 'spawn <project_path>/node_modules/optipng-bin/vendor/optipng ENOENT',
  stack: 'Error: spawn <project_path>/node_modules/optipng-bin/vendor/optipng ENOENT\n    at _errnoException (util.js:1041:11)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)\n    at onErrorNT (internal/child_process.js:374:16)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',
  fileName: '<project_path>/src/lib/bootstrap-colorpicker/dist/img/bootstrap-colorpicker/alpha.png',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-imagemin' }
```

turns out my `node_modules/optipng-bin/` has the following content:

```
node_modules/optipng-bin/
├── cli.js
├── index.js
├── lib
│   ├── index.js
│   └── install.js
├── license
├── package.json
└── readme.md

1 directory, 7 files
```

❌ `node_modules/optipng-bin/vendor/optipng` is not there! I don't know why :(

**Comment by GabLeRoux** [comment]
From the readme, it says

> ## API
> 
> Comes bundled with the following **lossless** optimizers:
> 
> - [gifsicle](https://github.com/imagemin/imagemin-gifsicle) — *Compress GIF images*
> - [jpegtran](https://github.com/imagemin/imagemin-jpegtran) — *Compress JPEG images*
> - [optipng](https://github.com/imagemin/imagemin-optipng) — *Compress PNG images*
> - [svgo](https://github.com/imagemin/imagemin-svgo) — *Compress SVG images*
> 
> These are bundled for convenience and most users will not need anything else.

Apparently, I had none of these correctly installed even after nuking my `node_modules` and running `npm i` right away. A workaround I've found is actually to install them by hand and add them to my `package.json`:

```bash
npm i --save optipng-bin jpegtran-bin imagemin-gifsicle imagemin-svgo
```

After doing so, binary was there, but actually, the right fix for me was to downgrade my node version to `node/6.11.5` (using [n](node/6.11.5)):
```bash
sudo n 6
npm install
```

🎉
