### ISSUE TITLE
Error: Cannot find module 'gulp-imagemin'

### ISSUE THREAD

**Issue by ForceLinkPRO** [sindresorhus/gulp-imagemin#291]
Gulpfile.js:
```
var gulp = require('gulp');
var cache = require('gulp-cache');
var imagemin = require('gulp-imagemin');

// Optimizing Images 
gulp.task('images', function() {
  return gulp.src('app/images/**/*.+(png|jpg|jpeg|gif|svg)')
    // Caching images that ran through imagemin
    .pipe(cache(imagemin({
      interlaced: true,
    })))
    .pipe(gulp.dest('dist/images'))
});
```
Error:
```
module.js:557
    throw err;
    ^

Error: Cannot find module 'gulp-imagemin'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/force/Шаблоны/gulp-starter-csstricks/gulpfile.js:7:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```
Help me please!

**Comment by ForceLinkPRO** [comment]
http://joxi.ru/1A5KVN6iK64xZm - versions plagins

```
********* ~/Шаблоны/gulp-starter-csstricks $ npm gulp -v
5.5.1
********* ~/Шаблоны/gulp-starter-csstricks $ npm gulp-cache -v
5.5.1
********* ~/Шаблоны/gulp-starter-csstricks $ npm gulp-imagemin -v
5.5.1
```

**Comment by ForceLinkPRO** [comment]
Command: 
`npm` i
```
Building: /usr/bin/node /home/force/Templates/gulp-starter-csstricks/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/home/force/Templates/gulp-starter-csstricks/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.3.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.3.0
gyp verb command install [ '9.3.0' ]
gyp verb install input version string "9.3.0"
gyp verb install installing version: 9.3.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.3.0
gyp verb build dir attempting to create "build" dir: /home/force/Templates/gulp-starter-csstricks/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/force/Templates/gulp-starter-csstricks/node_modules/node-sass/build'
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/usr/bin/node" "/home/force/Templates/gulp-starter-csstricks/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/force/Templates/gulp-starter-csstricks/node_modules/node-sass
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN project@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/force/.npm/_logs/2018-01-08T11_56_13_767Z-debug.log

```

**Comment by khyamay** [comment]
what's your node version ? I had same issue yesterday and found my node version was 0.12.0. Then I updated node to 7.5.0 and it working now.

**Comment by michaeljota** [comment]
You have an error with `node-sass`, probably you should setup your build tools to build native modules. Check `node-gyp` to know how to.
