### ISSUE TITLE
Error: Invalid SOS parameters for sequential JPEG

### ISSUE THREAD

**Issue by BigbangStudio** [sindresorhus/gulp-imagemin#306]
```
[01:54:48] Using gulpfile ~/Documents/myproject/public/gulpfile.js
[01:54:48] Starting 'minifyimage'...
[01:54:48] Finished 'minifyimage' after 7.98 ms

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Invalid SOS parameters for sequential JPEG

    at Promise.all.then.arr (/Users/bigbangstudio/Documents/myproject/public/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c /Users/bigbangstudio/Documents/myproject/public/node_modules/.bin/gulp minifyimage
Directory: /Users/bigbangstudio/Documents/myproject/public
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/bigbangstudio/Documents/myproject/public/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

-----------------------------------------------------------------------

And in my gulpile.js I wrote this:

```js
var gulp = require('gulp');
var imagemin = require('gulp-imagemin');

gulp.task('minifyimage', function(){
    gulp.src('uploads/*').pipe(imagemin()).pipe(gulp.dest('uploads'));
});
```

**Comment by XhmikosR** [comment]
Unrelated to gulp-imagemin, you should report it upstream to whatever jpeg optimizer you are using in your build (default jpegtran).
