### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by PilloryBarnDesign** [sindresorhus/gulp-imagemin#328]
Hi all,

I'm setting up a new gulpfile to use Gulp 4 and the only issue I'm getting with my tasks is the following:

```
/node_modules/gulp-imagemin/index.js:43
		...options
		^^^

SyntaxError: Unexpected token ...
```

It looks as thought it doesn't like the spread operator, has anyone come across this at all?

I'm using node v12.1.0 and gulp v4.0.2

**Comment by gdams** [comment]
I'm currently getting the same error:

```bash
/home/jenkins/.jenkins/openjdk-website/node_modules/gulp-imagemin/index.js:43
		...options
		^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

**Comment by gdams** [comment]
I fixed this by upgrading from Node 6 to Node 10

**Comment by PilloryBarnDesign** [comment]
> I fixed this by upgrading from Node 6 to Node 10

I changed from Node 12 to Node 11 and it appears to work, does yours work with 11 as well?
