### ISSUE TITLE
TypeError: Invalid host defined options

### ISSUE THREAD

**Issue by bobbyg603** [sindresorhus/gulp-imagemin#362]
In our gulpfile.esm.js everything works just fine until we import imagemin. As soon as we add imagemin and run gulp we get the following:

```
bugsplat-website-new % gulp
[15:33:57] Requiring external module esm
TypeError: Invalid host defined options
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js:10:15), <anonymous>:3:1)
    at requireOrImport (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js:24:7)
    at execute (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/index.js:211:24)
    at Liftoff.execute (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:201:12)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:191:5)
    at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:149:9
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:162:14
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:41:14
```

We're using node 14.17.4 and npm 7.22.0.

Can someone please help us get unstuck here? Thanks!

**Comment by Patta** [comment]
I can confirm this issue.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
