### ISSUE TITLE
Unable to install on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by malabya** [sindresorhus/gulp-imagemin#370]
Hi, I am not able to install the package on Ubuntu 20.04.3 LTS system.

Node - v14.19.0
npm - 6.14.16
yarn - 1.22.18

package.json 
`{
  "name": "xx",
  "version": "1.0.0",
  "description": "xx",
  "main": "Gulpfile.js",
  "license": "MIT",
  "scripts": {
    "watch": "gulp watch --development",
    "build:dev": "gulp build --development",
    "build": "gulp build --production",
    "clean": "gulp clean",
    "lint": "gulp lint",
    "lint:css:fix": "stylelint \"**/*.scss\" --fix"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/malabya/drupal-theme-generator"
  },
  "devDependencies": {
    "@babel/core": "^7.8.7",
    "@babel/preset-env": "^7.8.7",
    "babel-preset-env": "^1.7.0",
    "bootstrap": "^4.5.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-prettier": "^3.1.3",
    "gulp": "4",
    "gulp-autoprefixer": "^7.0.1",
    "gulp-babel": "^8.0.0",
    "gulp-clean": "^0.4.0",
    "gulp-eslint": "^6.0.0",
    "gulp-imagemin": "^7.1.0",
    "gulp-mode": "^1.0.2",
    "gulp-plumber": "^1.2.1",
    "gulp-rename": "^2.0.0",
    "gulp-sass": "^4.0.2",
    "gulp-sourcemaps": "^2.6.5",
    "gulp-stylelint": "^13.0.0",
    "gulp-uglify": "^3.0.2",
    "prettier": "^2.0.5",
    "stylelint": "^13.3.3",
    "stylelint-config-standard": "^20.0.0",
    "stylelint-order": "^4.1.0",
    "stylelint-scss": "^3.17.2"
  }
}
`

When I run yarn install 
`
[4/4] Building fresh packages...
[1/3] ⢀ gifsicle
[2/3] ⢀ mozjpeg
warning Error running install script for optional dependency: "/var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/optipng-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/optipng-bin
Output:
Command failed: /var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/optipng-bin/vendor/optipng --version
/var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/optipng-bin/vendor/optipng: 1: @@8�\u0001@8\b@\u001d\u001c\u0006\u0005@@@@@�\u0001�\u0001\b\u0003\u0004\u0002\u0002@\u0002@\u001c\u001c\u0001\u0001\u0005@@��\u0001��\u0001: not found
/var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/optipng-bin/vendor/optipng: 2: d: not found
/var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/optipng-bin/vendor/optipng: 1: Syntax error: \";\" unexpected
/var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/optipng-bin/vendor/optipng: 1: ELF\u0002\u0001\u0001\u0002: not found

optipng pre-build test failed
compiling from source
Error: Command failed: /bin/sh -c make install
pngrtran.c:99:1: warning: ‘png_rtran_ok’ defined but not used [-Wunused-function]
   99 | png_rtran_ok(png_structrp png_ptr, int need_IHDR)
      | ^~~~~~~~~~~~
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
pngxmem.c: In function ‘pngx_malloc_rows_extended’:
pngxmem.c:38:34: warning: comparison is always false due to limited range of data type [-Wtype-limits]
   38 |        (pngx_alloc_size_t)height > (pngx_alloc_size_t)(-1) / sizeof(png_bytep))
      |                                  ^
ar: `u' modifier ignored since `D' is the default (see `U')
/usr/bin/ld: ../libpng/libpng.a(pngrutil.o): in function `png_read_filter_row':
pngrutil.c:(.text+0x1f70): undefined reference to `png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:100: optipng] Error 1
make: *** [Makefile:14: install] Error 2

cd src/optipng && \\\nmake install && \\\ncd ../..
make[1]: Entering directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/optipng'
cd ../libpng && \\\nmake -f Makefile PNGLIBCONF_H_PREBUILT=pnglibconf.h.optipng && \\\ncd ../optipng
make[2]: Entering directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/libpng'
cp pnglibconf.h.optipng pnglibconf.h
gcc -c -I../zlib  -O2 -Wall -Wextra -o png.o png.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngerror.o pngerror.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngget.o pngget.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngmem.o pngmem.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngpread.o pngpread.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngread.o pngread.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngrio.o pngrio.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngrtran.o pngrtran.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngrutil.o pngrutil.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngset.o pngset.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngtrans.o pngtrans.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngwio.o pngwio.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngwrite.o pngwrite.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngwtran.o pngwtran.c
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngwutil.o pngwutil.c
ar rcs libpng.a png.o pngerror.o pngget.o pngmem.o pngpread.o pngread.o pngrio.o pngrtran.o pngrutil.o pngset.o pngtrans.o pngwio.o pngwrite.o pngwtran.o pngwutil.o
ranlib libpng.a
gcc -c -I../zlib  -O2 -Wall -Wextra -o pngtest.o pngtest.c
gcc  -L../zlib -o pngtest pngtest.o libpng.a -lz -lm
make[2]: Leaving directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/libpng'
cd ../opngreduc && \\\nmake -f Makefile libopngreduc.a && \\\ncd ../optipng
make[2]: Entering directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/opngreduc'
gcc -c  -O2 -Wall -Wextra  -I../libpng -o opngreduc.o opngreduc.c
ar cru libopngreduc.a opngreduc.o
ranlib libopngreduc.a
make[2]: Leaving directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/opngreduc'
cd ../gifread && \\\nmake -f Makefile libgifread.a && \\\ncd ../optipng
make[2]: Entering directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/gifread'
gcc -c  -O2 -Wall -Wextra -o gifread.o gifread.c
ar cru libgifread.a gifread.o
ranlib libgifread.a
make[2]: Leaving directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/gifread'
cd ../pnmio && \\\nmake -f Makefile libpnmio.a && \\\ncd ../optipng
make[2]: Entering directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/pnmio'
gcc -c  -O2 -Wall -Wextra -o pnmin.o pnmin.c
gcc -c  -O2 -Wall -Wextra -o pnmout.o pnmout.c
gcc -c  -O2 -Wall -Wextra -o pnmutil.o pnmutil.c
ar cru libpnmio.a pnmin.o pnmout.o pnmutil.o
ranlib libpnmio.a
make[2]: Leaving directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/pnmio'
cd ../minitiff && \\\nmake -f Makefile libminitiff.a && \\\ncd ../optipng
make[2]: Entering directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/minitiff'
gcc -c  -O2 -Wall -Wextra -o tiffread.o tiffread.c
gcc -c  -O2 -Wall -Wextra -o tiffutil.o tiffutil.c
ar cru libminitiff.a tiffread.o tiffutil.o
ranlib libminitiff.a
make[2]: Leaving directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/minitiff'
cd ../pngxtern && \\\nmake -f Makefile libpngxtern.a && \\\ncd ../optipng
make[2]: Entering directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/pngxtern'
gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxread.o pngxread.c
gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrbmp.o pngxrbmp.c
gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrgif.o pngxrgif.c
gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrjpg.o pngxrjpg.c
gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrpnm.o pngxrpnm.c
gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxrtif.o pngxrtif.c
gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxio.o pngxio.c
gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxmem.o pngxmem.c
gcc -c  -O2 -Wall -Wextra  -I../libpng -I../gifread -I../pnmio -I../minitiff -o pngxset.o pngxset.c
ar cru libpngxtern.a pngxread.o pngxrbmp.o pngxrgif.o pngxrjpg.o pngxrpnm.o pngxrtif.o pngxio.o pngxmem.o pngxset.o
ranlib libpngxtern.a
make[2]: Leaving directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/pngxtern'
gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o optipng.o optipng.c
gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o optim.o optim.c
gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o bitset.o bitset.c
gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o ioutil.o ioutil.c
gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o ratio.o ratio.c
gcc -c  -O2 -Wall -Wextra -I../cexcept  -I../libpng -I../opngreduc -I../pngxtern -o wildargs.o wildargs.c
gcc -s -o optipng optipng.o optim.o bitset.o ioutil.o ratio.o wildargs.o ../opngreduc/libopngreduc.a ../pngxtern/libpngxtern.a ../libpng/libpng.a  ../gifread/libgifread.a ../pnmio/libpnmio.a ../minitiff/libminitiff.a  -lz -lm
make[1]: Leaving directory '/tmp/fd54f00f-f481-4743-8e87-f69533a547c3/src/optipng'

    at /var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/execa/index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[1/3] ⡀ gifsicle
[2/3] ⢀ mozjpeg
warning Error running install script for optional dependency: "/var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/mozjpeg: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/mozjpeg
Output:
Command failed: /var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/mozjpeg/vendor/cjpeg -version
/var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/mozjpeg/vendor/cjpeg: 1: Syntax error: word unexpected (expecting \")\")

mozjpeg pre-build test failed
compiling from source
Error: Command failed: /bin/sh -c ./configure --enable-static --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix=\"/var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/mozjpeg/vendor\" --bindir=\"/var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/mozjpeg/vendor\" --libdir=\"/var/www/html/edc-dev.specbee.site/docroot/themes/custom/stelar/node_modules/mozjpeg/vendor\"
./configure: line 10331: PKG_PROG_PKG_CONFIG: command not found
./configure: line 10510: syntax error near unexpected token `libpng,'
./configure: line 10510: `PKG_CHECK_MODULES(libpng, libpng, HAVE_LIBPNG=1,'

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking how to run the C preprocessor... gcc -E
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) none
checking for ar... ar
checking the archiver (ar) interface... ar
checking dependency style of gcc... none
checking the archiver (ar) interface... (cached) ar
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert aarch64-unknown-linux-gnu file names to aarch64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert aarch64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking whether ln -s works... yes
checking size of size_t... 8
checking whether compiler supports pointers to undefined structures... yes
checking whether __SUNPRO_C is declared... no
checking for pow in -lm... yes
`

**Comment by rbruckheimer** [comment]
Lots of errors spitting out for me as well on install:
Ubuntu 20.04 on M1X, using gulp-imagemin 8.0.0

**Comment by sh4dowb** [comment]
ERR_REQUIRE_ESM error on node: 16 14 12 11 10 as well. ubuntu 20.04 lts, gulp latest version.
I have "fixed" this bullshit by not using gulp and even node at all, would recommend
