### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by KarelWintersky** [sindresorhus/gulp-imagemin#385]
```
import imagemin from 'gulp-imagemin';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:76:18)
    at wrapSafe (node:internal/modules/cjs/loader:1283:20)
    at Module._compile (node:internal/modules/cjs/loader:1328:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at requireOrImport (/var/.../node_modules/gulp-cli/lib/shared/require-or-import.js:20:11)
    at execute (/var/.../node_modules/gulp-cli/lib/versioned/^5.0.0/index.js:35:3)
```

My deps:
```
  "dependencies": {
    "gulp": "^5",
    "gulp-imagemin": "^9.1.0"
  }
```
Node v18.20.3

**Comment by robruiz** [comment]
Im getting this on Node 22 now. What is the fix?
