### ISSUE TITLE
Error That Fixes by Restarting

### ISSUE THREAD

**Issue by davidsilvasmith** [sindresorhus/gulp-imagemin#45]
I get the following error sometimes that is fixed by restarting my Macbook Air:

```
[19:42:41] Using gulpfile ~/apps/sowhatsbitcoin.com/gulpfile.js
[19:42:41] Starting 'crush'...

events.js:72 
    throw er; // Unhandled 'error' event
        ^
Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:647:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Socket.<anonymous> (child_process.js:968:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

Here is my task:

```
gulp.task('crush', function () {
    return gulp.src('./images/*')
        .pipe(imagemin({
            progressive: true,
            svgoPlugins: [{removeViewBox: false}],
            use: [pngcrush()],
            optimizationLevel: 7
        }))
        .pipe(gulp.dest('./images'));
});
```

**Comment by jinahya** [comment]
I'm a newbie to gulp and I couldn't solve this problem. I wish I have some Bitcoins. :)

```javascript
var paths = {
    src: 'src',
    src_markups: ['src/**/*.html'].concat(src_exclude),
    src_images: ['src/images/**/*.png', 'src/images/**/*.jpg', 'src/images/**/*.svg'].concat(src_exclude),
    src_javascripts: ['src/scripts/**/*.js'].concat(src_exclude),
    src_coffeescripts: ['src/scripts/**/*.coffee'].concat(src_exclude),
    src_typescripts: ['src/scripts/**/*.ts'].concat(src_exclude),
    src_css: ['src/styles/**/*.css'].concat(src_exclude),
    src_sass: ['src/styles/**/*.scss'].concat(src_exclude),
    dst: 'dst',
    dst_markups: 'dst',
    dst_images: 'dst/images',
    dst_scripts: 'dst/scripts',
    dst_styles: 'dst/styles',
    dpl: 'dpl'
};
// processes image files
gulp.task('images', function () {
    return gulp.src(paths.src_images)
            .pipe(gulpdebug({title: 'images'}))
            .pipe(gulpimagemin({
                progressive: true,
                svgoPlugins: [{removeViewBox: false}],
                use: [imageminpngquant()]
            }))
            .pipe(gulp.dest(paths.dst_images));
});
```
The output is.
```
[13:12:42] NODE_ENV: undefined
[13:12:42] environment: production
[13:12:42] Using gulpfile ~/gitcl/github.com/jinahya/frontend-example1/gulpfile.js
[13:12:42] Starting 'images'...
[13:12:42] images src/images/Example.png

events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: spawn /Users/onacit/gitcl/github.com/jinahya/frontend-example1/node_modules/optipng-bin/vendor/optipng ENOENT
  at exports._errnoException (util.js:856:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  at onErrorNT (internal/child_process.js:344:16)
  at _combinedTickCallback (node.js:377:13)
  at process._tickCallback (node.js:401:11)
```
