### ISSUE TITLE
Problem with using imagemin on linux with gulp@3.8.8

### ISSUE THREAD

**Issue by derberg** [sindresorhus/gulp-imagemin#81]
This is what I have in my project:

```
"gulp-imagemin": "^2.0.0"
```

On Mac all works fine but when I run my gulp tasks on: Linux Debian 3.14.12-1 I get the following error:

```
    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: write EPIPE
        at errnoException (net.js:904:11)
        at Object.afterWrite (net.js:720:19)

      at ChildProcess.<anonymous> (/node_modules/safeps/out/lib/safeps.js:165:23)
      at ChildProcess.emit (events.js:98:17)
      at maybeClose (child_process.js:755:16)
      at Process.ChildProcess._handle.onexit (child_process.js:822:5)
```

**Comment by nick-brown** [comment]
@kevva is there any `safeps` alternative that can be used here?  Currently this issue makes `gulp-imagemin` unusable on Debian and CentOS systems and the `safeps` maintainer has been unresponsive for 6 months on any issues.

**Comment by kevva** [comment]
It's not a direct dependency in imagemin/gulp-imagemin so we don't control where it's used.
